### ISSUE TITLE
Godot is using the outdated 4.2 version even though 4.3 is available

### ISSUE THREAD

**Issue by JanMaul** [fsfw-dresden/usb-live-linux#189]

**Comment by eMPee584** [comment]
Thanks for filing the report Jan, fixed by 016b706260d79c35c7961b5480ea44e5f45f88a6 ..
As godot4 has not been packaged for debian yet*, we install it _from a ZIP file_ :sweat_smile: and that brings about the obvious issue of not being easy to update automatically. I go through all external packages manually before preparing a new upload, the image you were using was from March 2024..

* it's being worked on, here's the relevant issue on the debian tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070845 and here's the merge request being worked on: https://salsa.debian.org/debian/godot/-/merge_requests/3 .. It's not trivial to package software 🤣
